/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package spormusabakasi;

import java.sql.*;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author gunes
 */
public class Fikstur extends javax.swing.JFrame {

    private DefaultListModel<String> evSahibiModel;
    private DefaultListModel<String> deplasmanModel;
    private DefaultListModel<String> evSahibiSkorModel;
    private DefaultListModel<String> deplasmanSkorModel;
    PuanTablosu puanTablosu = new PuanTablosu();
    //SporEkrani sporekrani_1 = new SporEkrani();
    private Map<String, Integer> skorlar;

    /**
     * Creates new form Fikstur
     */
    public Fikstur() {
        initComponents();
        initCustomComponents();
        setLocationRelativeTo(null); //ekranın ortasında açılır.
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    private void initCustomComponents() {
        evSahibiModel = new DefaultListModel<>();
        deplasmanModel = new DefaultListModel<>();
        evSahibiSkorModel = new DefaultListModel<>();
        deplasmanSkorModel = new DefaultListModel<>();

        skorlar = new HashMap<>();

        // Örnek takımlar ve skorlar
        String[] evSahibiTakimlar = {"Takım A", "Takım B", "Takım C"};
        String[] deplasmanTakimlar = {"Takım X", "Takım Y", "Takım Z"};
        int[] evSahibiSkorlar = {0, 0, 0};
        int[] deplasmanSkorlar = {0, 0, 0};

        for (int i = 0; i < evSahibiTakimlar.length; i++) {
            evSahibiModel.addElement(evSahibiTakimlar[i]);
            deplasmanModel.addElement(deplasmanTakimlar[i]);
            evSahibiSkorModel.addElement(String.valueOf(evSahibiSkorlar[i]));
            deplasmanSkorModel.addElement(String.valueOf(deplasmanSkorlar[i]));

            skorlar.put(evSahibiTakimlar[i], evSahibiSkorlar[i]);
            skorlar.put(deplasmanTakimlar[i], deplasmanSkorlar[i]);
        }

        jListEvSahibi.setModel(evSahibiModel);
        jListDeplasman.setModel(deplasmanModel);
        jListEvSahibiSkor.setModel(evSahibiSkorModel);
        jListDeplasmanSkor.setModel(deplasmanSkorModel);

        jButtonGolEkle.addActionListener(e -> golEkle());
        jButton1.addActionListener(e -> golIptal());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPaneEvSahibi = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListEvSahibi = new javax.swing.JList<>();
        jScrollPaneEvSahibiSkor = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListEvSahibiSkor = new javax.swing.JList<>();
        jScrollPaneDeplasmanSkor = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListDeplasmanSkor = new javax.swing.JList<>();
        jScrollPaneDeplasman = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListDeplasman = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButtonGolEkle = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jRadioButtonGalibiyet = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButtonMaglubiyet = new javax.swing.JRadioButton();
        jButtonpuanTablosunaEkle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jListEvSahibi.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListEvSahibi);

        jScrollPaneEvSahibi.setViewportView(jScrollPane1);

        jScrollPane3.setViewportView(jListEvSahibiSkor);

        jScrollPaneEvSahibiSkor.setViewportView(jScrollPane3);

        jScrollPane4.setViewportView(jListDeplasmanSkor);

        jScrollPaneDeplasmanSkor.setViewportView(jScrollPane4);

        jScrollPane2.setViewportView(jListDeplasman);

        jScrollPaneDeplasman.setViewportView(jScrollPane2);

        jLabel1.setText("Ev Sahibi Takım");

        jLabel2.setText("Skor");

        jLabel3.setText("Skor");

        jLabel4.setText("Deplasman Takımı");

        jLabel5.setText("VS");

        jTextField1.setText("jTextField1");

        jLabel6.setText("Skorunu değiştirmek istediğiniz takım adını girin : ");

        jButtonGolEkle.setText("Gol");

        jButton1.setText("Gol İptal");

        buttonGroup1.add(jRadioButtonGalibiyet);
        jRadioButtonGalibiyet.setText("Galibiyet");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Beraberlik");

        buttonGroup1.add(jRadioButtonMaglubiyet);
        jRadioButtonMaglubiyet.setText("Mağlubiyet");

        jButtonpuanTablosunaEkle.setText("Puan Tablosuna Ekle");
        jButtonpuanTablosunaEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonpuanTablosunaEkleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPaneEvSahibi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPaneEvSahibiSkor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPaneDeplasmanSkor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jScrollPaneDeplasman, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonGolEkle)
                                        .addGap(61, 61, 61)
                                        .addComponent(jButton1))
                                    .addComponent(jTextField1)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonMaglubiyet, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonpuanTablosunaEkle))
                            .addComponent(jRadioButtonGalibiyet, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneEvSahibi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPaneEvSahibiSkor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPaneDeplasmanSkor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPaneDeplasman, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel5)))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGolEkle)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonGalibiyet)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(jButtonpuanTablosunaEkle))
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonMaglubiyet)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonpuanTablosunaEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonpuanTablosunaEkleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonpuanTablosunaEkleActionPerformed

    private void golEkle() {
        String takimAdi = jTextField1.getText().trim();
        if (takimAdi.isEmpty() || !skorlar.containsKey(takimAdi)) {
            JOptionPane.showMessageDialog(this, "Geçerli bir takım adı girin.");
            return;
        }
        int yeniSkor = skorlar.get(takimAdi) + 1;
        skorlar.put(takimAdi, yeniSkor);
        guncelleSkorListeleri();
    }

    private void golIptal() {
        String takimAdi = jTextField1.getText().trim();
        if (takimAdi.isEmpty() || !skorlar.containsKey(takimAdi)) {
            JOptionPane.showMessageDialog(this, "Geçerli bir takım adı girin.");
            return;
        }
        int yeniSkor = Math.max(0, skorlar.get(takimAdi) - 1);
        skorlar.put(takimAdi, yeniSkor);
        guncelleSkorListeleri();
    }

    private void guncelleSkorListeleri() {
        for (int i = 0; i < evSahibiModel.getSize(); i++) {
            evSahibiSkorModel.set(i, String.valueOf(skorlar.get(evSahibiModel.getElementAt(i))));
            deplasmanSkorModel.set(i, String.valueOf(skorlar.get(deplasmanModel.getElementAt(i))));
        }
    }
   private void puanTablosunaEkle() {
        for (int i = 0; i < evSahibiModel.getSize(); i++) {
            String evSahibi = evSahibiModel.getElementAt(i);
            String deplasman = deplasmanModel.getElementAt(i);
            int evSahibiSkor = Integer.parseInt(evSahibiSkorModel.getElementAt(i));
            int deplasmanSkor = Integer.parseInt(deplasmanSkorModel.getElementAt(i));

            if (evSahibiSkor > deplasmanSkor) {
                puanTablosu.puanGuncelle(evSahibi, 3);
                puanTablosu.puanGuncelle(deplasman, 0);
            } else if (evSahibiSkor < deplasmanSkor) {
                puanTablosu.puanGuncelle(evSahibi, 0);
                puanTablosu.puanGuncelle(deplasman, 3);
            } else {
                puanTablosu.puanGuncelle(evSahibi, 1);
                puanTablosu.puanGuncelle(deplasman, 1);
            }
        }

        puanTablosu.setVisible(true);
    }
   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fikstur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fikstur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fikstur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fikstur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fikstur().setVisible(true);
    
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonGolEkle;
    private javax.swing.JButton jButtonpuanTablosunaEkle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jListDeplasman;
    private javax.swing.JList<String> jListDeplasmanSkor;
    private javax.swing.JList<String> jListEvSahibi;
    private javax.swing.JList<String> jListEvSahibiSkor;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButtonGalibiyet;
    private javax.swing.JRadioButton jRadioButtonMaglubiyet;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPaneDeplasman;
    private javax.swing.JScrollPane jScrollPaneDeplasmanSkor;
    private javax.swing.JScrollPane jScrollPaneEvSahibi;
    private javax.swing.JScrollPane jScrollPaneEvSahibiSkor;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    
}
