/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package spormusabakasi;

import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gunes
 */
public class PuanTablosu extends javax.swing.JFrame {
    Connection con;
    PreparedStatement pst;
    private DefaultTableModel tableModel;
    private Map<String, Integer> puanlar;

    /**
     * Creates new form PuanTablosu
     */
    
    public PuanTablosu() {
        initComponents();
        initCustomComponents();
        initializeDBConnection();
        
        setLocationRelativeTo(null); //ekranın ortasında açılır.
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        
    }
    private void initializeDBConnection() {
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/spor", "root", "Bg541523.");
            //pst = con.createStatement(); 
        } catch (SQLException ex) {
            Logger.getLogger(Spor1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     private void initCustomComponents() {
        puanlar = new HashMap<>();
        tableModel = (DefaultTableModel) jTable1.getModel();
    }
      public DefaultTableModel getTableModel() {
        return (DefaultTableModel) jTable1.getModel();
  }
  public void addTeam(String teamName) {
        DefaultTableModel model = getTableModel();
        int rowCount = model.getRowCount();
        int colCount = model.getColumnCount();

        // Boş hücre bul ve takım adını ekle
        for (int row = 0; row < rowCount; row++) {
            if (model.getValueAt(row, 0) == null || model.getValueAt(row, 0).toString().isEmpty()) {
                model.setValueAt(teamName, row, 0);
                for (int col = 1; col < colCount; col++) {
                    model.setValueAt(0, row, col); // Diğer sütunları sıfırla
                }
                return; // Takım eklendi, metottan çık
            }
        }
        // Eğer boş hücre bulunamazsa, yeni satır ekle
        model.addRow(new Object[]{teamName, 0, 0, 0, 0});
    }
  
   public void puanGuncelle(String takim, int yeniPuan) {
        if (puanlar.containsKey(takim)) {
            int eskiPuan = puanlar.get(takim);
            puanlar.put(takim, eskiPuan + yeniPuan);
            guncellePuanTablosu();
        }
    }
    private void guncellePuanTablosu() {
        for (int i = 0; i < tableModel.getRowCount(); i++) {
            String takim = (String) tableModel.getValueAt(i, 0);
            tableModel.setValueAt(puanlar.get(takim), i, 1);
        }
    }
      public void takimEkle(String takim) {
        if (!puanlar.containsKey(takim)) {
            puanlar.put(takim, 0);
            tableModel.addRow(new Object[]{takim, 0});
        }
    }
  
  
  


      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Takımlar", "Galibiyet", "Beraberlik", "Mağlubiyet", "Puan"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PuanTablosu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PuanTablosu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PuanTablosu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PuanTablosu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PuanTablosu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

  

    
}
